(()=>{
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const cfg=window.TH3FLOW_CONFIG||{}; const live=cfg.mode==='live'&&cfg.supabaseUrl&&!cfg.supabaseUrl.includes('YOUR_PROJECT')&&cfg.supabasePublishableKey&&!cfg.supabasePublishableKey.includes('REPLACE_ME');
const sb=live&&window.supabase?window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey):null;
let data={session:null,stats:{rounds:0,wins:0,losses:0,ties:0,net_pnl_minor:0,best_streak:0},entries:[],adds:[],activeDays:0,referrals:0,activeRefs:0,refEarnings:0};
const money=n=>{const x=Number(n||0)/100;return (x<0?'-':'')+'₦'+Math.abs(x).toLocaleString('en-NG',{maximumFractionDigits:2,minimumFractionDigits:0})};
const A=(id,name,desc,cat,rarity,glyph,test,progress)=>({id,name,desc,cat,rarity,glyph,test,progress});
const cat=[
A('first_flow','First Flow','Complete your first valid race.','Origins','common','◉',d=>d.stats.rounds>=1,d=>[d.stats.rounds,1]),A('first_win','Called It','Record your first winning call.','Origins','common','▲',d=>d.stats.wins>=1,d=>[d.stats.wins,1]),A('first_loss','Scar Tissue','Finish your first race on the wrong side.','Origins','common','×',d=>d.stats.losses>=1,d=>[d.stats.losses,1]),A('first_tie','Dead Heat','Take part in a race whose start and finish Bid are identical.','Origins','rare','=',d=>d.stats.ties>=1,d=>[d.stats.ties,1]),A('ten_rounds','Into The Flow','Complete 10 valid races.','Origins','common','10',d=>d.stats.rounds>=10,d=>[d.stats.rounds,10]),A('fifty_rounds','Known Current','Complete 50 valid races.','Endurance','rare','50',d=>d.stats.rounds>=50,d=>[d.stats.rounds,50]),A('hundred_rounds','Century','Complete 100 valid races.','Endurance','epic','100',d=>d.stats.rounds>=100,d=>[d.stats.rounds,100]),A('250_rounds','Deep Water','Complete 250 valid races.','Endurance','epic','250',d=>d.stats.rounds>=250,d=>[d.stats.rounds,250]),A('500_rounds','The Long Current','Complete 500 valid races.','Endurance','legendary','500',d=>d.stats.rounds>=500,d=>[d.stats.rounds,500]),A('1000_rounds','A Thousand Calls','Complete 1,000 valid races.','Endurance','legendary','1K',d=>d.stats.rounds>=1000,d=>[d.stats.rounds,1000]),
A('win3','Three Clean','Win 3 races.','Accuracy','common','III',d=>d.stats.wins>=3,d=>[d.stats.wins,3]),A('win10','Ten Correct','Win 10 races.','Accuracy','common','X',d=>d.stats.wins>=10,d=>[d.stats.wins,10]),A('win25','Twenty Five','Win 25 races.','Accuracy','rare','XXV',d=>d.stats.wins>=25,d=>[d.stats.wins,25]),A('win50','Fifty Calls','Win 50 races.','Accuracy','epic','L',d=>d.stats.wins>=50,d=>[d.stats.wins,50]),A('acc55','Edge','Hold 55%+ accuracy across at least 20 races.','Accuracy','rare','55',d=>d.stats.rounds>=20&&d.stats.wins/d.stats.rounds>=.55,d=>[Math.round((d.stats.wins/Math.max(1,d.stats.rounds))*100),55]),A('acc60','Sharp','Hold 60%+ accuracy across at least 50 races.','Accuracy','epic','60',d=>d.stats.rounds>=50&&d.stats.wins/d.stats.rounds>=.60,d=>[Math.round((d.stats.wins/Math.max(1,d.stats.rounds))*100),60]),A('acc65','Unnatural','Hold 65%+ accuracy across at least 100 races.','Accuracy','legendary','65',d=>d.stats.rounds>=100&&d.stats.wins/d.stats.rounds>=.65,d=>[Math.round((d.stats.wins/Math.max(1,d.stats.rounds))*100),65]),
A('streak2','Back To Back','Win 2 races consecutively.','Streaks','common','Ⅱ',d=>d.stats.best_streak>=2,d=>[d.stats.best_streak,2]),A('streak3','Hot Hand','Win 3 races consecutively.','Streaks','common','Ⅲ',d=>d.stats.best_streak>=3,d=>[d.stats.best_streak,3]),A('streak5','On Fire','Win 5 races consecutively.','Streaks','rare','Ⅴ',d=>d.stats.best_streak>=5,d=>[d.stats.best_streak,5]),A('streak7','Seven Deep','Win 7 races consecutively.','Streaks','epic','Ⅶ',d=>d.stats.best_streak>=7,d=>[d.stats.best_streak,7]),A('streak10','Untouched','Win 10 races consecutively.','Streaks','legendary','Ⅹ',d=>d.stats.best_streak>=10,d=>[d.stats.best_streak,10]),
A('green','Above Water','Reach positive lifetime net flow.','Flow','common','+',d=>d.stats.rounds>=1&&d.stats.net_pnl_minor>0,d=>[d.stats.net_pnl_minor>0?1:0,1]),A('net10k','Current +10K','Reach +₦10,000 lifetime net flow.','Flow','rare','₦',d=>d.stats.net_pnl_minor>=1_000_000,d=>[Math.max(0,d.stats.net_pnl_minor),1_000_000]),A('net50k','Current +50K','Reach +₦50,000 lifetime net flow.','Flow','epic','₦',d=>d.stats.net_pnl_minor>=5_000_000,d=>[Math.max(0,d.stats.net_pnl_minor),5_000_000]),A('net100k','Six Figures','Reach +₦100,000 lifetime net flow.','Flow','legendary','₦',d=>d.stats.net_pnl_minor>=10_000_000,d=>[Math.max(0,d.stats.net_pnl_minor),10_000_000]),
A('scale1','Conviction','Add to an existing position before entry closes.','Scaling','common','↗',d=>d.adds.length>d.entries.length,d=>[Math.max(0,d.adds.length-d.entries.length),1]),A('scale5','Build The Position','Record 5 scale-ins across your races.','Scaling','rare','↗',d=>Math.max(0,d.adds.length-d.entries.length)>=5,d=>[Math.max(0,d.adds.length-d.entries.length),5]),A('scale25','Layered','Record 25 scale-ins.','Scaling','epic','≋',d=>Math.max(0,d.adds.length-d.entries.length)>=25,d=>[Math.max(0,d.adds.length-d.entries.length),25]),
A('days3','Return Current','Play on 3 distinct days.','Endurance','common','☰',d=>d.activeDays>=3,d=>[d.activeDays,3]),A('days7','A Week In','Play on 7 distinct days.','Endurance','rare','7D',d=>d.activeDays>=7,d=>[d.activeDays,7]),A('days15','Regular','Play on 15 distinct days.','Endurance','epic','15D',d=>d.activeDays>=15,d=>[d.activeDays,15]),A('days30','Resident','Play on 30 distinct days.','Endurance','legendary','30D',d=>d.activeDays>=30,d=>[d.activeDays,30]),
];
const future=[
['higher_first','Upstream','Win your first HIGHER call.','Flow','common','▲'],['lower_first','Downstream','Win your first LOWER call.','Flow','common','▼'],['both_day','Two Directions','Win HIGHER and LOWER on the same day.','Flow','rare','↕'],['all_durations','Every Distance','Win a 1m, 5m and 15m race.','Flow','rare','1·5·15'],['contra40','Against The Crowd','Win while your side holds less than 40% of the pool.','Flow','rare','40'],['contra25','Against The Current','Win while your side holds less than 25% of the pool.','Flow','epic','25'],['contra10','Alone In The Water','Win while your side holds less than 10% of the pool.','Flow','legendary','10'],['photo1','Photo Finish','Win by a tiny finishing-price margin.','Accuracy','rare','·'],['photo5','Five Fine Margins','Collect five Photo Finish wins.','Accuracy','epic','···'],['late1','Last Call','Enter during the final permitted entry window and win.','Flow','rare','⌛'],['early1','First In','Enter near the opening of a pool and win.','Flow','common','◷'],['scale_win','Double Down Without Doubling','Scale into a position and win the race.','Scaling','rare','↗▲'],['scale3_win','Three Layers','Add to the same position at least twice and win.','Scaling','epic','≋▲'],['tie5','Still Water','Take part in five exact-price ties.','Origins','epic','=5'],['season_join','First Current','Complete a race in Season 01.','Season','seasonal','I'],['season50','Half The Field','Finish a season in the top 50%.','Season','seasonal','50%'],['season25','Quarter Current','Finish a season in the top 25%.','Season','seasonal','25%'],['season10','Top Current','Finish a season in the top 10%.','Season','seasonal','10%'],['season5','Five Percent','Finish a season in the top 5%.','Season','seasonal','5%'],['season1','One Percent','Finish a season in the top 1%.','Season','seasonal','1%'],['season100','The Hundred','Finish a season inside the top 100.','Season','seasonal','#100'],['season10rank','The Ten','Finish a season inside the top 10.','Season','seasonal','#10'],['podium','Podium','Finish a season in the top three.','Season','seasonal','Ⅲ'],['champ','Champion','Finish a season ranked #1.','Season','legendary','Ⅰ'],['ref1','First Invite','Bring your first genuinely active referred player.','Social','common','+1'],['ref5','Flow Builder','Bring 5 active referred players.','Social','rare','+5'],['ref25','Crowd Puller','Bring 25 active referred players.','Social','epic','+25'],['ref100','The Network','Bring 100 active referred players.','Social','legendary','+100'],['share1','Leave A Mark','Share your first TH3FLOW result card.','Social','common','↗'],['city10','Home Current','Finish a week inside your city top 10.','Social','epic','⌂'],['global100','Visible','Finish a week inside the global top 100.','Social','epic','◎']
].map(x=>A(...x,d=>false,d=>[0,1]));
const achievements=[...cat,...future];
function xpFor(d){return Math.max(0,d.stats.rounds*35+d.stats.wins*20+d.stats.ties*10+Math.min(5000,Math.max(0,d.stats.net_pnl_minor/10000)))}
function render(){const s=data.stats,earned=achievements.filter(a=>a.test(data));const xp=Math.floor(xpFor(data)),level=Math.floor(xp/500)+1,inLevel=xp%500;$('#level').textContent=String(level).padStart(2,'0');$('#xpLabel').textContent=xp.toLocaleString()+' XP';$('#xpNext').textContent=`Next level · ${(level*500).toLocaleString()} XP`;$('#xpBar').style.width=(inLevel/5)+'%';$('#stRounds').textContent=Number(s.rounds||0).toLocaleString();$('#stAccuracy').textContent=s.rounds?Math.round(s.wins/s.rounds*100)+'%':'—';$('#stNet').textContent=money(s.net_pnl_minor);$('#stStreak').textContent=s.best_streak||0;$('#stTies').textContent=s.ties||0;$('#stTrophies').textContent=earned.length;$('#earnedCount').textContent=earned.length;$('#totalCount').textContent=achievements.length;$('#identityLine').textContent=data.session?(data.session.user.email||'Signed in'):(live?'Sign in to reveal your record':'Demo cabinet');renderGrid(currentFilter);$('#seasonScore').textContent=Math.floor(xp*.72).toLocaleString();$('#seasonLevel').textContent=String(Math.floor(xp/650)+1).padStart(2,'0');$('#seasonDays').textContent=data.activeDays||'—';renderPreview();renderRefs();}
let currentFilter='all';
function card(a){const e=a.test(data),[v,t]=a.progress(data),pct=e?100:Math.min(100,Math.max(0,(Number(v)||0)/(Number(t)||1)*100));return `<article class="trophy ${a.rarity} ${e?'':'locked'}"><div class="glyph">${a.glyph}</div><div class="rarity">${a.rarity} · ${a.cat}</div>${e?'<div class="earned">earned</div>':''}<h3>${a.name}</h3><p>${a.desc}</p><div class="progress"><div class="progressline"><i style="width:${pct}%"></i></div><small>${e?'Complete':`${Math.min(Number(v)||0,Number(t)||1).toLocaleString()} / ${(Number(t)||1).toLocaleString()}`}</small></div></article>`}
function renderGrid(f='all'){$('#trophyGrid').innerHTML=achievements.filter(a=>f==='all'||a.cat===f).map(card).join('')}
function renderPreview(){const ids=['season_join','season50','season10','season1','podium','champ'];$('#seasonPreview').innerHTML=ids.map(id=>card(achievements.find(a=>a.id===id))).join('')}
function renderRefs(){const ids=['ref1','ref5','ref25','ref100'];$('#refPreview').innerHTML=ids.map(id=>card(achievements.find(a=>a.id===id))).join('');$('#refEarnings').textContent=money(data.refEarnings);$('#refInvites').textContent=data.referrals;$('#refActive').textContent=data.activeRefs;$('#refTier').textContent=data.activeRefs>=100?'Syndicate':data.activeRefs>=25?'Partner':data.activeRefs>=5?'Scout':'Referral';$('#refLink').value='Referral tracking backend not enabled yet';}
async function load(){if(!sb){data.stats={rounds:37,wins:21,losses:15,ties:1,net_pnl_minor:1823400,best_streak:4};data.entries=Array(37).fill({});data.adds=Array(42).fill({});data.activeDays=9;render();return}const {data:{session}}=await sb.auth.getSession();data.session=session;if(!session){render();return}const uid=session.user.id;const [st,en,ad]=await Promise.all([sb.from('player_stats').select('*').eq('user_id',uid).maybeSingle(),sb.from('race_entries').select('id,created_at,settled').eq('user_id',uid).order('created_at',{ascending:false}).limit(1000),sb.from('race_entry_additions').select('id,entry_id,created_at').eq('user_id',uid).order('created_at',{ascending:false}).limit(1000)]);if(st.data)data.stats=st.data;data.entries=en.data||[];data.adds=ad.data||[];data.activeDays=new Set(data.entries.filter(x=>x.settled).map(x=>String(x.created_at).slice(0,10))).size;render()}
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.toggle('on',x===b));$$('.view').forEach(v=>v.classList.toggle('on',v.id===b.dataset.view+'View'))});$$('.filter').forEach(b=>b.onclick=()=>{currentFilter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('on',x===b));renderGrid(currentFilter)});
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1500)}
$('#copyRef').onclick=()=>toast('Referral tracking backend comes next');$('#accountBtn').onclick=()=>{if(data.session&&sb){sb.auth.signOut().then(()=>location.reload())}else location.href='../play/'};
load();
})();
